import org.apache.thrift.server.TServer;
import org.apache.thrift.server.TServer.Args;
import org.apache.thrift.server.TThreadPoolServer;
import org.apache.thrift.transport.TServerSocket;
import org.apache.thrift.transport.TServerTransport;

// import code generated by Apache Thrift compiler
import hello.*;

public class HelloWorldServer {

    public static HelloWorldHandler handler;

    public static HelloWorldService.Processor processor;

    public static void myserver(HelloWorldService.Processor processor) {
        TServerTransport serverTransport = new TServerSocket(8080);
        TServer server = new TThreadPoolServer(new TThreadPoolServer.Args(serverTransport).processor(processor));
        server.serve();
    }

    // main function
    public static void main(String [] args) {
        handler = new HelloWorldHandler();
        processor = new HelloWorldService.Processor(handler);

        Runnable server = new Runnable() {
            public void run() {
                myserver(processor);
            }
        };

        new Thread(server).start();
    }

}
